shorturl/urls.py
from django.conf.urls import url

from shorturl import views

app_name = "shorturl"


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^(?P<hash>\w{10})/$', views.redirect, name="shorturl"),
]

webutilits/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.views.decorators.cache import cache_page
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps import views   # Представление


from core.sitemap import HomeSitemap, sitemap_filesharing
from core import views as core

handler404 = "core.views.handler404"

sitemaps = {
    "home": HomeSitemap,
    "filesharing": GenericSitemap(sitemap_filesharing, priority=0.5),
}


urlpatterns = [
    url(
        r'^sitemap\.xml$',
        cache_page(86400)(views.index),
        {'sitemaps': sitemaps}
    ),
    url(
        r'^sitemap-(?P<section>\w+)\.xml$',
        cache_page(86400)(views.sitemap),
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),

    url('^privatenotes/', include('privatenote.urls', namespace='privatenote')),
    url('^filesharing/', include('filesharing.urls', namespace='filesharing')),
    url('^shorturl/', include('shorturl.urls', namespace='shorturl')),

    url('^$', core.index),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models


class UserCounter(models.Model):
    ip = models.CharField(max_length=15, null=False, blank=False)

    date = models.DateTimeField(auto_now=True, null=False, blank=False)

    object_id = models.PositiveIntegerField()
    content_type = models.ForeignKey(ContentType, on_delete=models.PROTECT)

    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        abstract = True


class Download(UserCounter):
    pass


class Hint(UserCounter):
    pass

core/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'core/index.html')


def handler404(request, msg="Старница не найдена :(", status=404, *args, **argv):
    context = {
        "title_": "Ошибка 404",
        "message": msg,
        "robots": "noindex,nofollow"
    }
    return render(request, "core/error.html", context, status=status)

templates/core/error.html
{% extends 'base.html' %}
{% load static %}
{% block title_ %}{{title_}}{%endblock%}
{% block content %}
    <div class="main">
      <div class="title">{{title_}}</div>
      <div class="error-body">
        {{message}}
      </div>
    </div>
{% endblock %}

templates/core/index.html
{% extends 'base.html' %}
{% block content %}
<div class="main-index">
<h1 class="title">Приветствуем вас на сайте на сайте WebUtilits.ru</h1>
<p>Сайт основан в учебных началах и возможно будет развиваться дальше, в качестве портфолио написанных мною веб утилит и не только.</p>
<p>На текщий момент доступны следующие инструменты:</p>
<ul>
  <li><a href="{% url 'filesharing:index' %}">Файлообменник</a></li>
  <li><a href="{% url 'shorturl:index' %}">Сокращение ссылок</a></li>
  <li><a href="{% url 'privatenote:index' %}">Приватные записки</a></li>
</ul>
<p>Все утилиты бесплатны и доступны любому желающему их проэксперементировать.<br>
Убедительная просьба, не использовать сайт в коммерческих целях.</p>
</div>
{% endblock %}