filesharing/urls.py
from django.conf.urls import url

from filesharing import views

app_name = "filesharing"



urlpatterns = [
    url(r'^files/delete/(?P<file_id>\d*)/$', views.delete, name="delete"),
    url(r'^files/download/(?P<file_id>\d*)/$', views.download, name="download"),
    url(r'^files/(?P<file_id>\d*)/$', views.file, name="file"),
    url(r'^$', views.upload, name="index"),
]

shorturl/urls.py
from django.conf.urls import url

from shorturl import views

app_name = "shorturl"


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^(?P<hash>\w{10})/$', views.redirect, name="shorturl"),
]

webutilits/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

from django.views.decorators.cache import cache_page
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps import views   # Представление


from core.sitemap import HomeSitemap, sitemap_filesharing
from core import views as core

handler404 = "core.views.handler404"

sitemaps = {
    "home": HomeSitemap,
    "filesharing": GenericSitemap(sitemap_filesharing, priority=0.5),
}


urlpatterns = [
    url(
        r'^sitemap\.xml$',
        cache_page(86400)(views.index),
        {'sitemaps': sitemaps}
    ),
    url(
        r'^sitemap-(?P<section>\w+)\.xml$',
        cache_page(86400)(views.sitemap),
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),

    url('^privatenotes/', include('privatenote.urls', namespace='privatenote')),
    url('^filesharing/', include('filesharing.urls', namespace='filesharing')),
    url('^shorturl/', include('shorturl.urls', namespace='shorturl')),

    url('^$', core.index),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filesharing/models.py
from django.db import models
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation

from core.models import Hint, Download


class File(models.Model):
    # Модель, кранящая сведения об опубликованном файле и путь до него
    file = models.FileField(upload_to='uploads/filesharing/%Y/%m/%d/')
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True, null=True)

    # Отметка времени, когда будет удалён файл
    time_delete = models.DateTimeField()

    password_for_delete = models.CharField(
        max_length=40,
        blank=True,
        null=True
    )
    password_for_download = models.CharField(
        max_length=40,
        blank=True,
        null=True
    )

    pub_date = models.DateTimeField(auto_now=True)
    creator_ip = models.CharField(max_length=15)

    hints = GenericRelation(Hint, related_name="files")
    download = GenericRelation(Download, related_name="files")

    def get_absolute_url(self):
        return reverse('filesharing:file', args={self.id})

filesharing/forms.py
from hashlib import md5

from django import forms

from filesharing.models import File
from django.core.exceptions import ValidationError


DELETE_TIME_CHOICE = [
    ('1', '1 час'),
    ('2', '1 день'),
    ('3', '7 дней'),
    ('4', '30 дней'),
]


class UploadForm(forms.ModelForm):
    time_delete = forms.ChoiceField(choices=DELETE_TIME_CHOICE)

    class Meta:
        model = File
        fields = [
            'file',
            'description',
            'password_for_delete',
            'password_for_download'
        ]

        widgets = {
            'password_for_delete': forms.PasswordInput(
                attrs={'placeholder': 'Пароль для удаления'}
            ),
            'password_for_download': forms.PasswordInput(
                attrs={'placeholder': 'Пароль для скачивания'}
            ),
            'description': forms.TextInput(
                attrs={'placeholder': 'Описание файла'}
            )
        }

    def clean_password_for_delete(self):
        password = self.cleaned_data.get('password_for_delete', None)
        if not password:
            return password
        return md5(password.encode('utf8')).hexdigest()

    def clean_password_for_download(self):
        password = self.cleaned_data.get('password_for_download', None)
        if not password:
            return password
        return md5(password.encode('utf8')).hexdigest()

    def clean_file(self):
        file = self.cleaned_data.get('file', None)
        if not file:
            raise ValidationError('Поле файла - обязательно.')

        max_megabyte = 50
        max_bits = max_megabyte * 1024 * 1024

        if file.size > max_bits:
            raise ValidationError('Файл слишком большой. Максимальный размер файла %i MiB.') % max_megabyte

        return file


class DeletePasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Пароль для удаления'}
    ))

    def clean_password(self):
        password = self.cleaned_data.get('password', None)
        if not password:
            raise ValidationError('Поле пароля - обязательно.')
        return md5(password.encode('utf8')).hexdigest()


class DownloadPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Пароль для скачивания'}
    ))

    def clean_password(self):
        password = self.cleaned_data.get('password', None)
        if not password:
            raise ValidationError('Поле пароля - обязательно.')
        return md5(password.encode('utf8')).hexdigest()

filesharing/views.py
import os
from datetime import timedelta, datetime

from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, StreamingHttpResponse

from webutilits.settings import MEDIA_ROOT
from core.utilits import get_client_ip, incCountHit, incCountDownload
from core.tasks import delete_file_schedule
from filesharing.models import File
from filesharing.forms import (
    UploadForm,
    DeletePasswordForm,
    DownloadPasswordForm
)

DELETE_TIME_DELTA = {
    '1': timedelta(hours=1),
    '2': timedelta(days=1),
    '3': timedelta(days=7),
    '4': timedelta(days=30),
}


def upload(request):
    context = {}
    form = UploadForm(request.POST or None, request.FILES or None)

    if request.method == 'POST' and form.is_valid():
        file_object = form.save(commit=False)

        choice_delta_del = form.cleaned_data.get('time_delete', 3)

        file_object.name = form.cleaned_data['file'].name
        file_object.creator_ip = get_client_ip(request)
        file_object.time_delete = datetime.now(tz=timezone.utc) + DELETE_TIME_DELTA[choice_delta_del]

        file_object.save()

        delete_file_schedule(file_object.id, schedule=DELETE_TIME_DELTA[choice_delta_del])

        context['file_url'] = request.build_absolute_uri(
            file_object.get_absolute_url()
        )
    context['form'] = form
    return render(request, 'filesharing/upload.html', context)


def file(request, file_id):
    context = dict()

    context['file'] = get_object_or_404(File, id=file_id)
    context['delete_form'] = DeletePasswordForm()
    context['download_form'] = DownloadPasswordForm()
    context['file_url'] = request.build_absolute_uri(
        context['file'].get_absolute_url()
    )

    # Инкрементирую счетчик просмотров
    incCountHit(request, context['file'])

    return render(request, 'filesharing/file.html', context)


def checkPassword(request, file_id, field_name, form):
    # Совершает проверку над запросом, переданными данными и паролем
    if request.method == "POST":
        file = get_object_or_404(File, id=file_id)
        form = form(request.POST)
        if form.is_valid():
            if form.cleaned_data['password'] == getattr(file, field_name):
                return file
            return JsonResponse({'status': 0, 'errors': ['Не правильный пароль']})
        return JsonResponse({'status': 0, 'errors': form.errors})
    return JsonResponse({'status': 0, 'errors': ['Разрешены только POST запросы']})


def download(request, file_id):
    # Реализует загрузку файла
    file = get_object_or_404(File, id=file_id)
    if file.password_for_download:
        # Проверка пароля
        response = checkPassword(request, file_id, 'password_for_download', DownloadPasswordForm)
        if type(response) is JsonResponse:
            return response

    if request.is_ajax():
        # Если запрос пришел на проверку пароля
        return JsonResponse({'status': 1})

    response = StreamingHttpResponse(open(MEDIA_ROOT+file.file.name, 'rb'))
    response['content_type'] = "application/octet-stream"
    response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file.name)

    incCountDownload(request, file)

    return response


def delete(request, file_id):
    # Удаляет файл, если изначально был установлен пароль на его удаление, в
    # ином случае, это не возможно
    file = get_object_or_404(File, id=file_id)
    if not file.password_for_download:
        return JsonResponse({'status': 0, 'errors': ['Удаление - не возможно']})

    response = checkPassword(request, file_id, 'password_for_delete', DeletePasswordForm)
    if type(response) is JsonResponse:
        return response

    response.delete()
    return JsonResponse({'status': 1})

templates/filesharing/file.html
{% extends 'base.html' %}
{% load static %}
{% load qr_code %}


{% block title %}Скачать файл {{file.name}}{% endblock %}
{% block title_ %}Скачать файл {{file.name}}{% endblock %}

{% block description %}{% if file.description %}{{file.description}}{% else %}Вы можете бесплатно скачать данный файл у нас на сайте.{% endif %}{% endblock %}
{% block description_ %}{% if file.description %}{{file.description}}{% else %}Вы можете бесплатно скачать данный файл у нас на сайте.{% endif %}{% endblock %}

{% block keywords %}{{file.name}},скачать бесплатно{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/filesharing/file.css' %}">
{% endblock %}

{% block js %}
<script type="text/javascript" src="{% static 'js/filesharing/file.js' %}"></script>
{% endblock %}

{% block content %}
<div class="blockdownloadfile main-form vtcenter">
  <div class="title"><div style="width: 24.6mm;"></div>{{file.name}}{% qr_from_text file_url size="T" %}</div>
  <p><b>Описание: </b>{% if file.description %}{{file.description}}{% else %}отсутствует{% endif %}</p>
  <form method="POST" action="{% url 'filesharing:download' file_id=file.id %}" name="download" class="act_password">{% if file.password_for_download %}{{download_form.password}}<input type="submit" value="Скачать"></input>{% else %}<input type="submit" value="Скачать" class="nopass">{% endif %}{% csrf_token %}</form>
  {% if file.password_for_delete %}<form method="POST" action="{% url 'filesharing:delete' file_id=file.id %}" name="delete" class="act_password">{% csrf_token %}{{delete_form.password}}<input type="submit" value="Удалить"></input></form>{% endif %}
  <div class="meta">
    <div class="listdate">
      <div class="date"><b>Дата публикации: </b><span>{{file.pub_date|date:"m.d.Y G:i" }}</span></div>
      <div class="date"><b>Дата удаления файла: </b><span>{{file.time_delete|date:"m.d.Y G:i" }}</span></div>
    </div>
    <div class="listcount">
      <div class="counthints">{{file.hints.count}}<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"viewBox="0 0 512.006 512.006" style="enable-background:new 0 0 512.006 512.006;" xml:space="preserve"><g><g><path d="M507.082,244.168l-48.763-48.763C342.838,80.53,169.122,80.535,54.287,195.371L4.991,244.106C1.809,247.255,0.011,251.54,0,256.01c-0.011,4.476,1.759,8.767,4.918,11.932l48.769,48.769c57.67,57.367,129.972,86.048,202.302,86.048c72.324,0,144.671-28.698,202.358-86.088l48.735-48.735c3.154-3.148,4.924-7.422,4.924-11.881C512.006,251.596,510.236,247.322,507.082,244.168z M434.606,292.875c-101.812,101.302-255.389,101.291-357.184,0.034l-36.781-36.787l37.341-36.916c101.38-101.38,254.706-101.375,356.596,0l36.848,36.848L434.606,292.875z"/></g></g><g><g><path d="M256,155.789c-55.289,0-100.271,44.982-100.271,100.271c0,55.289,44.982,100.271,100.271,100.271s100.271-44.982,100.271-100.271C356.271,200.771,311.289,155.789,256,155.789z M256,322.721c-36.759,0-66.661-29.902-66.661-66.661S219.241,189.4,256,189.4s66.655,29.908,66.655,66.661C322.655,292.814,292.759,322.721,256,322.721z"/></g></g><g><g><path d="M256,210.126v33.611c6.913,0,12.324,5.417,12.324,12.324c0,6.907-5.411,12.324-12.324,12.324c-6.913,0-12.324-5.417-12.324-12.324h-33.611c0,25.326,20.609,45.934,45.934,45.934c25.331,0,45.934-20.603,45.934-45.934S281.326,210.126,256,210.126z"/></g></g></svg></div>
      <div class="countdownloads">{{file.download.count}}<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve"><g><g><g><path d="M256,285c11.046,0,20-8.954,20-20V20c0-11.046-8.954-20-20-20c-11.046,0-20,8.954-20,20v245C236,276.046,244.954,285,256,285z"/><path d="M212.472,367.324c0.034,0.034,0.067,0.068,0.101,0.102c11.701,11.701,27.069,17.549,42.437,17.549c15.356,0,30.71-5.842,42.388-17.521L408.114,257.17c7.826-7.795,7.851-20.458,0.056-28.284c-7.795-7.825-20.458-7.851-28.284-0.056L269.142,339.142c-3.778,3.777-8.8,5.858-14.142,5.858c-5.323,0-10.329-2.065-14.102-5.817L132.243,228.959c-7.754-7.867-20.418-7.957-28.284-0.203c-7.866,7.754-7.957,20.417-0.203,28.284L212.472,367.324z"/><path d="M492,412c-11.046,0-20,8.954-20,20c0,22.056-17.944,40-40,40H80c-22.056,0-40-17.944-40-40c0-11.046-8.954-20-20-20s-20,8.954-20,20c0,44.112,35.888,80,80,80h352c44.112,0,80-35.888,80-80C512,420.954,503.046,412,492,412z"/></g></g></g></svg></div>
    </div>
  </div>
</div>
{% endblock %}

{% block popup %}
<div class="main-message">
  <div class="block-message">
    <div class="body-message">
      <div class="title-message">Удалить файл</div>
      <div class="message">Вы уверены, что хотите совершить это действие?</div>
    </div>
    <div class="manipulate-message-menu">
      <div class="confirm" onclick="$('div.main-message').css({'display': 'none'});last_function(last_function_elem);">Да</div>
      <div class="cancel" onclick="$('div.main-message').css({'display': 'none'});">Нет</div>
    </div>
  </div>
</div>
{% endblock %}

templates/filesharing/upload.html
{% extends 'base.html' %}
{% load static %}
{% load qr_code %}

{% block title %}Бесплатный файлообменник{% endblock %}
{% block title_ %}Бесплатный файлообменник{% endblock %}

{% block description %}На нашем сайте, вы можете бесплатно загружать и делиться файлами со всем миром.{% endblock %}
{% block description_ %}На нашем сайте, вы можете бесплатно загружать и делиться файлами со всем миром.{% endblock %}

{% block keywords %}файлообменник, бесплатный хостинг файлов{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/filesharing/upload.css' %}">
{% endblock %}

{% block form %}
<form action="{% url 'filesharing:index' %}" method="POST" enctype="multipart/form-data" name="uploadFile" class="main-form vtcenter">
  {%csrf_token%}
  <div class="title">Файлообменник</div>
  {{form.file}}
  {{form.description}}
  <div class="passwords">
    {{form.password_for_delete}}{{form.password_for_download}}
  </div>
  <div class="timelifeandpush">
  <select id="id_time_delete" name="time_delete">
    <option value="3">Время жизни файла</option>
    {% for option in form.time_delete %}{{option}}{% endfor %}
  </select>
  <input type="submit" value="Загрузить">
  </div>
  {% if file_url %}<div class="link-to-file"><span class='link-to-file'>Файл загружен и доступен по <a href='{{file_url}}'>ссылке</a></span>{% qr_from_text file_url size="T" %}</div>{% endif %}
  {{form.errors}}
</form>
{% endblock %}

{% block js %}<script src="{% static 'js/filesharing/upload.js' %}"></script>{% endblock %}